import { Flex, Heading } from "@chakra-ui/layout";
import { BasicLayout } from "components/layout/BasicLayout";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <Flex flex="1" align="center">
          <Heading w="100%" textAlign="center">
            Home Page
          </Heading>
        </Flex>
      </BasicLayout>
    </div>
  );
};

export default Home;
